# Completions for archx and archc

complete -c archx -s d -l dest -r -d 'Destination directory'
complete -c archx -s f -l force -d 'Overwrite'
complete -c archx -s s -l strip -r -d 'Strip leading components'
complete -c archx -s p -l password -r -d 'Password'
complete -c archx -s t -l threads -r -d 'Threads'
complete -c archx -s q -l quiet -d 'Quiet'
complete -c archx -l no-progress -d 'Disable progress'
complete -c archx -l list -d 'List contents'
complete -c archx -l dry-run -d 'Show actions without executing'
complete -c archx -l help -d 'Help'
complete -c archx -xa '(__fish_complete_suffix .zip .7z .rar .tar .tar.gz .tgz .tar.xz .txz .tar.zst .tzst .tar.bz2 .tbz2 .tar.lz4 .tlz4 .xz .gz .bz2 .zst)'

complete -c archc -s F -l format -xa 'auto zip 7z tar.gz tar.xz tar.zst tar.bz2 tar.lz4 tar' -d 'Archive format'
complete -c archc -s L -l level -r -d 'Compression level'
complete -c archc -s t -l threads -r -d 'Threads'
complete -c archc -s e -l encrypt -d 'Enable encryption'
complete -c archc -s p -l password -r -d 'Password'
complete -c archc -s C -l chdir -r -d 'Change working directory'
complete -c archc -s i -l include-glob -r -d 'Include glob'
complete -c archc -s x -l exclude-glob -r -d 'Exclude glob'
complete -c archc -s q -l quiet -d 'Quiet'
complete -c archc -l no-progress -d 'Disable progress'
complete -c archc -l smart -d 'Smart format selection'
complete -c archc -l dry-run -d 'Show actions without executing'
complete -c archc -l help -d 'Help'
